var a = {
  success: true,
  value: [
    {
      code: 'page',
      dictTypeCode: 'MaterialType',
      dictTypeId: 11,
      id: 1101,
      level: 1,
      name: '页面',
      order: 0,
      parentCode: '',
      parentId: 0,
      subList: [
        {
          code: '-',
          dictTypeCode: 'MaterialType',
          dictTypeId: 11,
          id: 110101,
          level: 2,
          name: '产品投续保页面',
          order: 0,
          parentCode: '',
          parentId: 1101,
          subList: [
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11010101,
              level: 3,
              name: '产品投保页面（测试环境）',
              order: 0,
              parentCode: '',
              parentId: 110101,
              subList: [],
            },
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11010102,
              level: 3,
              name: '产品续保页面',
              order: 0,
              parentCode: '',
              parentId: 110101,
              subList: [],
            },
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11010103,
              level: 3,
              name: '产品投保页面迭代（生产环境）',
              order: 0,
              parentCode: '',
              parentId: 110101,
              subList: [],
            },
          ],
        },
        {
          code: '-',
          dictTypeCode: 'MaterialType',
          dictTypeId: 11,
          id: 110102,
          level: 2,
          name: '产品标准长图',
          order: 0,
          parentCode: '',
          parentId: 1101,
          subList: [
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11010201,
              level: 3,
              name: '产品标准长图',
              order: 0,
              parentCode: '',
              parentId: 110102,
              subList: [],
            },
          ],
        },
        {
          code: '-',
          dictTypeCode: 'MaterialType',
          dictTypeId: 11,
          id: 110103,
          level: 2,
          name: '产品宣传海报',
          order: 0,
          parentCode: '',
          parentId: 1101,
          subList: [
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11010301,
              level: 3,
              name: '产品宣传海报',
              order: 0,
              parentCode: '',
              parentId: 110103,
              subList: [],
            },
          ],
        },
        {
          code: '-',
          dictTypeCode: 'MaterialType',
          dictTypeId: 11,
          id: 110104,
          level: 2,
          name: '产品宣传折页',
          order: 0,
          parentCode: '',
          parentId: 1101,
          subList: [
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11010401,
              level: 3,
              name: '产品宣传折页',
              order: 0,
              parentCode: '',
              parentId: 110104,
              subList: [],
            },
          ],
        },
        {
          code: '-',
          dictTypeCode: 'MaterialType',
          dictTypeId: 11,
          id: 110105,
          level: 2,
          name: '活动页面',
          order: 0,
          parentCode: '',
          parentId: 1101,
          subList: [
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11010501,
              level: 3,
              name: '活动页面',
              order: 0,
              parentCode: '',
              parentId: 110105,
              subList: [],
            },
          ],
        },
        {
          code: '-',
          dictTypeCode: 'MaterialType',
          dictTypeId: 11,
          id: 110109,
          level: 2,
          name: '理赔服务宣传页面',
          order: 0,
          parentCode: '',
          parentId: 1101,
          subList: [
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11010901,
              level: 3,
              name: '理赔服务宣传页面',
              order: 0,
              parentCode: '',
              parentId: 110109,
              subList: [],
            },
          ],
        },
        {
          code: '-',
          dictTypeCode: 'MaterialType',
          dictTypeId: 11,
          id: 110110,
          level: 2,
          name: '增值服务宣传页面',
          order: 0,
          parentCode: '',
          parentId: 1101,
          subList: [
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11011001,
              level: 3,
              name: '增值服务宣传页面',
              order: 0,
              parentCode: '',
              parentId: 110110,
              subList: [],
            },
          ],
        },
        {
          code: '-',
          dictTypeCode: 'MaterialType',
          dictTypeId: 11,
          id: 110111,
          level: 2,
          name: '其他页面',
          order: 0,
          parentCode: '',
          parentId: 1101,
          subList: [
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11011101,
              level: 3,
              name: '其他页面',
              order: 0,
              parentCode: '',
              parentId: 110111,
              subList: [],
            },
          ],
        },
      ],
    },
    {
      code: 'copywriting',
      dictTypeCode: 'MaterialType',
      dictTypeId: 11,
      id: 1102,
      level: 1,
      name: '文案',
      order: 0,
      parentCode: '',
      parentId: 0,
      subList: [
        {
          code: '-',
          dictTypeCode: 'MaterialType',
          dictTypeId: 11,
          id: 110201,
          level: 2,
          name:
            '文案一（软文、媒体平台投放、新闻稿、视频脚本、理赔服务宣传文、增值服务宣传文、直播文案）',
          order: 0,
          parentCode: '',
          parentId: 1102,
          subList: [
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11020101,
              level: 3,
              name: '软文',
              order: 0,
              parentCode: '',
              parentId: 110201,
              subList: [],
            },
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11020102,
              level: 3,
              name: '媒体平台投放',
              order: 0,
              parentCode: '',
              parentId: 110201,
              subList: [],
            },
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11020103,
              level: 3,
              name: '新闻稿',
              order: 0,
              parentCode: '',
              parentId: 110201,
              subList: [],
            },
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11020104,
              level: 3,
              name: '视频脚本',
              order: 0,
              parentCode: '',
              parentId: 110201,
              subList: [],
            },
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11020105,
              level: 3,
              name: '理赔服务宣传文',
              order: 0,
              parentCode: '',
              parentId: 110201,
              subList: [],
            },
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11020106,
              level: 3,
              name: '增值服务宣传文',
              order: 0,
              parentCode: '',
              parentId: 110201,
              subList: [],
            },
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11020107,
              level: 3,
              name: '直播文',
              order: 0,
              parentCode: '',
              parentId: 110201,
              subList: [],
            },
          ],
        },
        {
          code: '-',
          dictTypeCode: 'MaterialType',
          dictTypeId: 11,
          id: 110202,
          level: 2,
          name: '文案二（精品问答、众安精灵、客服语料）',
          order: 0,
          parentCode: '',
          parentId: 1102,
          subList: [
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11020201,
              level: 3,
              name: '精品问答',
              order: 0,
              parentCode: '',
              parentId: 110202,
              subList: [],
            },
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11020202,
              level: 3,
              name: '众安精灵',
              order: 0,
              parentCode: '',
              parentId: 110202,
              subList: [],
            },
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11020203,
              level: 3,
              name: '客服语料',
              order: 0,
              parentCode: '',
              parentId: 110202,
              subList: [],
            },
          ],
        },
        {
          code: '-',
          dictTypeCode: 'MaterialType',
          dictTypeId: 11,
          id: 110203,
          level: 2,
          name: '文案三（短信、Push、理赔案例）',
          order: 0,
          parentCode: '',
          parentId: 1102,
          subList: [
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11020301,
              level: 3,
              name: '短信',
              order: 0,
              parentCode: '',
              parentId: 110203,
              subList: [],
            },
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11020302,
              level: 3,
              name: 'Push',
              order: 0,
              parentCode: '',
              parentId: 110203,
              subList: [],
            },
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11020303,
              level: 3,
              name: '理赔案例',
              order: 0,
              parentCode: '',
              parentId: 110203,
              subList: [],
            },
          ],
        },
        {
          code: '-',
          dictTypeCode: 'MaterialType',
          dictTypeId: 11,
          id: 110204,
          level: 2,
          name: '文案四（直营医典库）',
          order: 0,
          parentCode: '',
          parentId: 1102,
          subList: [
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11020401,
              level: 3,
              name: '直营医典库',
              order: 0,
              parentCode: '',
              parentId: 110204,
              subList: [],
            },
          ],
        },
        {
          code: '-',
          dictTypeCode: 'MaterialType',
          dictTypeId: 11,
          id: 110205,
          level: 2,
          name: '其他文案',
          order: 0,
          parentCode: '',
          parentId: 1102,
          subList: [
            {
              code: '-',
              dictTypeCode: 'MaterialType',
              dictTypeId: 11,
              id: 11020501,
              level: 3,
              name: '其他文案',
              order: 0,
              parentCode: '',
              parentId: 110205,
              subList: [],
            },
          ],
        },
      ],
    },
  ],
}

const levelTree = (trees) => {
  if (!Array.isArray(trees)) {
    trees = [trees]
  }
  const res = []
  while (trees.length > 0) {
    res.push({ nodes: trees, value: [], options: [] })
    trees = trees.reduce((pre, cur) => {
      return [...pre, ...cur.subList]
    }, [])
  }
  console.log(res)
  return res
}

levelTree(a.value)
